ALTER TYPE "PhotoCategory" ADD VALUE IF NOT EXISTS 'CHECKIN_ESTABLISHMENT';
ALTER TYPE "PhotoCategory" ADD VALUE IF NOT EXISTS 'BEFORE_1';
ALTER TYPE "PhotoCategory" ADD VALUE IF NOT EXISTS 'BEFORE_2';
ALTER TYPE "PhotoCategory" ADD VALUE IF NOT EXISTS 'AFTER_1';
ALTER TYPE "PhotoCategory" ADD VALUE IF NOT EXISTS 'AFTER_2';
