ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'GPS_MISSING';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'MISSING_REQUIRED_PHOTO';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TOO_FAST_VISIT';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TOO_LONG_VISIT';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'INCONSISTENT_FINISH';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'SYNC_FAILURE';
